### ISSUE TITLE
crosswikis_wikipedia_p_e_m.txt

### ISSUE THREAD

**Issue by BeerTai** [wujsAct/DGCN_EL#7]
Hi, I can't find the file ' crosswikis_wikipedia_p_e_m.txt' and 'yago_p_e_m.txt' in mongo_utils.py. Where can I find them? thanks

**Comment by 1292917512** [comment]
This come from https://github.com/dalab/deep-ed

**Comment by PKUTAN** [comment]
how did you get ' crosswikis_wikipedia_p_e_m.txt' and 'yago_p_e_m.txt'  from https://github.com/dalab/deep-ed, Can you show some more details?

**Comment by PKUTAN** [comment]
> This come from https://github.com/dalab/deep-ed

did you successfully run the code?

**Comment by 1292917512** [comment]
It worked, but it was already a long time since it was successful


| |
13295563344
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/5/2023 20:11 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [wujsAct/WWW2020-DGCN_EL] crosswikis_wikipedia_p_e_m.txt (#7) |

This come from https://github.com/dalab/deep-ed

did you successfully run the code?
